// Crear un objeto que se llame textos registro con los textos de error de cada campo

export const textosRegistro = {
  nombreCampo: {
    nombre: 'Nombre',
    apellidos: 'Apellidos',
    dni: 'DNI/NIE',
    mail: 'Correo electrónico',
    telefono: 'Teléfono',
    clave: 'Contraseña',
    clave2: 'Repetir contraseña',
  },

  mensajesError: {
    nombre: 'Su nombre es obligatorio',
    apellidos: 'Sus apellidos son obligatorios',
    dni: 'Su DNI/NIE es obligatorio',
    email: 'Su correo electrónico es obligatorio',
    telefono: 'Su teléfono es obligatorio',
    clave: 'Su contraseña es obligatoria',
    clave2: 'Repetir contraseña es obligatorio',
    legal: 'Tiene que aceptar el Aviso Legal y la Política de privacidad',
  },
  datosDeclarante: {
    nombre: 'MANUEL',
    apellidos: 'GÓMEZ DE LA SERNA',
    dni: '12345678Z',
    clave: 'Password12',
    clave2: 'Password12',
    mail: 'jc@saysawa.com',
    telefono: '600000000',
    casilla: '999,5',
    banco: 'ES0000000000000000000000',
    soltero: '.click()',
    casado: '.click()',
    divorciado: '.click()',
    viudo: '.click()',
    expedicionDni: '2019-01-01',
    caducidadDni: '2028-12-01',
    fechaNacimiento: '1973-08-12',
    casilla: '1000.05',
    direccion: 'Mi calle, 1. Madrid',
    cp: '28001',
  },

  datosConyugue: {
    nombre: 'Maria',
    apellidos: 'Villacís López',
    dni: '12345678Z',
    clave: 'IsaguapaM',
    mail: 'mmvillacis@gmail.com',
    telefono: '600000000',
    casilla: '500',
    banco: 'ES0000000000000000000000',
    soltero: '.click()',
    casado: '.click()',
    divorciado: '.click()',
    viudo: '.click()',
    expedicionDni: '2018-01-01',
    caducidadDni: '2028-12-01',
    fechaNacimiento: '1973-12-03',
    direccion: 'Mi calle, 1. Madrid',
    cp: '28001',
  },
  datosHijo1: {
    nombre: 'David Gómez Villacis',
    apellidos: 'Gómez Villacís',
    dni: '12345678Z',
    fechaNacimiento: '1993-12-01',
  },
  datosHijo2: {
    nombre: 'Elena',
    apellidos: 'Gómez Villacís',
    dni: '12345678Z',
    fechaNacimiento: '1997-12-01',
  },
  ascendiente1: {
    nombre: 'Elena Gómez Pérez',
    apellidos: 'Gómez Pérez',
    dni: '12345678Z',
    fechaNacimiento: '1937-12-01',
  },
};
